name: Filters and Path Step

on:
  workflow_dispatch:
  
  pull_request:
    types:
      - opened
      - reopened
    paths:
      - "app/index.html"
env:
  WORKFLOW_VAR: "Workflow"

jobs:
  take-action:
    runs-on: ubuntu-24.04
    steps:
      - run: |
          echo "=== $GITHUB_EVENT_NAME payload ==="
          echo "=== $WORKFLOW_VAR payload ==="