name: Passing Variables

on:
  workflow_dispatch:
    
jobs:
  generate-variables:
    runs-on: ubuntu-latest
    outputs:
      conn: ${{steps.generate-variables.outputs.conn}}
    steps:
      - name: Generate Conn Variable
        id: generate-variables
        run: |
          conn=bar
          echo "conn=${conn}" >> "$GITHUB_OUTPUT"
          echo "FOO=${conn}" >> "$GITHUB_ENV"
      - name: Inspect Variables
        run: |
          echo "$FOO"
          echo ${{steps.generate-variables.outputs.conn}}
          echo "$GITHUB_ENV"
          echo "$GITHUB_OUTPUT"