name: Secrets and Variables

on:
  workflow_dispatch:
    
jobs:
  staging:
    runs-on: ubuntu-latest
    environment: Staging
    env:
      SQL_CONNECTION_STRING: ${{secrets.SQL_CONNECTION_STRING}}
      DATABASE_NAME: ${{vars.DATABASE_NAME}}
    steps:
      - name: Inspect Variables
        run: |
          echo "$SQL_CONNECTION_STRING"
          echo $DATABASE_NAME

  production:
    needs: staging
    runs-on: ubuntu-latest
    environment: Production
    env:
      SQL_CONNECTION_STRING: ${{secrets.SQL_CONNECTION_STRING}}
      DATABASE_NAME: ${{vars.DATABASE_NAME}}
    steps:
      - name: Inspect Variables
        run: |
          echo "$SQL_CONNECTION_STRING"
          echo $DATABASE_NAME