name: Generate Artifacts and Upload/Download
on:
  workflow_dispatch:
    
jobs:
  restore-cache:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.demo-cache.outputs.cache-hit }}
    steps:
      - name: Restore cache
        id: demo-cache
        uses: actions/cache@v5
        with:
          path: example-artifacts
          key: demo-cache-v1

      - name: Populate cache directory
        if: steps.demo-cache.outputs.cache-hit != 'true'
        run: |
          echo "Cache miss - generating contents"
          mkdir -p example-artifacts
          date > example-artifacts/artifact.txt

      - name: Save cache
        if: steps.demo-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v5
        with:
          path: example-artifacts
          key: demo-cache-v1
      
      - name: Verify cache status
        run: |
          echo "cache-hit? -> %{{ steps.demo-cache.outputs.cache-hit }}"
          cat example-artifacts/artifact.txt


  generate-upload-artifacts:
    needs: [restore-cache]
    runs-on: ubuntu-latest
    if: needs.restore-cache.outputs.cache-hit != 'true'
    steps:
      - name: Create artifacts
        run: | 
          echo "This will be stored as an artifact!" > artifact.txt
          echo "Generated by artifact-producer job on $(date)" >> artifact.txt
      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: example-artifacts
          path: artifact.txt

  consumer:
    runs-on: ubuntu-latest
    if: always() && (needs.restore-cache.result == 'success')
    needs: [generate-upload-artifacts, restore-cache]
    steps:
      - name: Download Artifacts
        if: needs.generate-upload-artifacts.result == 'success'
        uses: actions/download-artifact@v7
        with:
          name: example-artifacts

      - name: Print artifact content
        if: needs.generate-upload-artifacts.result == 'success'
        run: cat artifact.txt

      - name: Fallback if cache was hit
        if: needs.generate-upload-artifacts.result == 'skipped'
        run: echo "Skipped artifact download because we had a cache hit in the primary job!"